import { existsSync } from "node:fs";
import { join } from "node:path";
import { PrismaClient } from "@prisma/client";
import { categories, catalogProducts } from "../app/_data/mock";
import { REVIEW_AUTHORS, reviewPoolForCategory } from "../app/_data/review-content";

// Load Next.js-convention env files for local runs (`tsx prisma/seed.ts`).
// On Vercel/CI, DATABASE_URL is already in process.env and these files are
// absent, so this is a no-op.
for (const file of [".env", ".env.local"]) {
  if (existsSync(file)) process.loadEnvFile(file);
}

const prisma = new PrismaClient();

// Join path segments under public/. Used by resolveVariantImages() below to
// probe for real product photos before falling back to a demo SVG. Generate
// demos with: npx tsx scripts/generate-demo-images.ts
function publicPath(...parts: string[]): string {
  return join(process.cwd(), "public", ...parts);
}

// Stable per-product RNG so reseeds produce the same data.
function rngFromId(id: string): () => number {
  let h = 2166136261 >>> 0;
  for (let i = 0; i < id.length; i++) {
    h ^= id.charCodeAt(i);
    h = Math.imul(h, 16777619) >>> 0;
  }
  return () => {
    h = (Math.imul(h, 1664525) + 1013904223) >>> 0;
    return h / 0xffffffff;
  };
}

function pick<T>(arr: T[], rng: () => number): T {
  return arr[Math.floor(rng() * arr.length)];
}

// Short, consistent default description for the T-shirt catalog (rendered as
// markdown on the product page). Product-agnostic so every item reads the same.
const DEFAULT_DESCRIPTION = `Premium 220 GSM T-Shirt made with a comfortable 65% cotton and 35% polyester blend. Designed for everyday wear with a soft feel, durable fabric, and a clean modern fit. The material is breathable, long-lasting, and perfect for casual outfits, streetwear, or high-quality DTF printed designs.

**Wash Care:** Wash inside out with cold or normal water. Use hand wash or gentle machine wash. Do not bleach, tumble dry, or iron directly on the print. Dry in shade to maintain fabric quality and print durability.`;

// Resolve variant image files under public/products/<productId>/<colorSlug>/<role>/1.jpg..8.jpg.
// Falls back to a single demo SVG so a bare checkout still has an image.
function resolveVariantImages(productId: string, colorSlug: string, role: "card" | "detail"): string[] {
  const urls: string[] = [];
  for (let n = 1; n <= 8; n++) {
    const candidates = [`${n}.jpg`, `${n}.jpeg`, `${n}.png`, `${n}.webp`];
    const found = candidates.find((file) =>
      existsSync(publicPath("products", productId, colorSlug, role, file)),
    );
    if (!found) break;
    urls.push(`/products/${productId}/${colorSlug}/${role}/${found}`);
  }
  if (urls.length === 0) {
    // Demo fallback: main.svg at the product root (generated by scripts/generate-demo-images.ts).
    urls.push(`/products/${productId}/main.svg`);
  }
  return urls;
}

function stockFor(seedKey: string): number {
  const rng = rngFromId(seedKey + ":stock");
  return 5 + Math.floor(rng() * 21); // 5..25
}

async function main() {
  const existingCategoryCount = await prisma.category.count();
  if (existingCategoryCount > 0 && process.env.FORCE_SEED !== "true") {
    console.log(
      `[seed] Skipping: ${existingCategoryCount} categories already present. ` +
      `Set FORCE_SEED=true to override.`,
    );
    return;
  }

  if (existingCategoryCount > 0) {
    console.log(
      `[seed] FORCE_SEED=true detected; reseeding over ${existingCategoryCount} existing categories.`,
    );
  }

  // Categories
  for (const c of categories) {
    await prisma.category.upsert({
      where: { slug: c.slug },
      update: { name: c.name, image: c.image },
      create: { slug: c.slug, name: c.name, image: c.image },
    });
  }

  for (const p of catalogProducts) {
    await prisma.product.upsert({
      where: { id: p.id },
      update: {
        name: p.name, price: p.price, originalPrice: p.originalPrice ?? null,
        description: DEFAULT_DESCRIPTION, categorySlug: p.category,
      },
      create: {
        id: p.id, name: p.name, price: p.price, originalPrice: p.originalPrice ?? null,
        description: DEFAULT_DESCRIPTION, categorySlug: p.category,
      },
    });

    // Rebuild variants (delete cascades to VariantImage + VariantSizeStock).
    await prisma.productVariant.deleteMany({ where: { productId: p.id } });
    for (let vi = 0; vi < p.variants.length; vi++) {
      const v = p.variants[vi];
      const variant = await prisma.productVariant.create({
        data: {
          productId: p.id,
          color: v.color,
          colorSlug: v.colorSlug,
          swatchHex: v.swatchHex ?? null,
          sku: v.sku ?? null,
          price: v.price ?? null,
          originalPrice: v.originalPrice ?? null,
          sortOrder: vi,
          archived: false,
        },
      });

      const cardUrls = resolveVariantImages(p.id, v.colorSlug, "card");
      const detailUrls = resolveVariantImages(p.id, v.colorSlug, "detail");
      const imageRows = [
        ...cardUrls.map((url, i) => ({ variantId: variant.id, url, role: "CARD", sortOrder: i })),
        ...detailUrls.map((url, i) => ({ variantId: variant.id, url, role: "DETAIL", sortOrder: i })),
      ];
      await prisma.variantImage.createMany({ data: imageRows });

      await prisma.variantSizeStock.createMany({
        data: v.sizes.map((s) => ({
          variantId: variant.id,
          size: s.size,
          stock: s.stock ?? stockFor(`${p.id}:${v.colorSlug}:${s.size}`),
        })),
      });
    }

    // Reviews (product-level, shared across colors) — unchanged logic, keyed on p.id.
    await prisma.review.deleteMany({ where: { productId: p.id } });
    const rng = rngFromId(p.id + ":reviews");
    const count = 5 + Math.floor(rng() * 6);
    const reviews = Array.from({ length: count }, () => {
      const daysAgo = Math.floor(rng() * 90);
      const createdAt = new Date(Date.now() - daysAgo * 86400_000);
      const tpl = pick(reviewPoolForCategory(p.category), rng);
      return {
        productId: p.id, authorName: pick(REVIEW_AUTHORS, rng),
        rating: tpl.rating, title: tpl.title, body: tpl.body,
        createdAt, synthetic: true, approved: true,
      };
    });
    await prisma.review.createMany({ data: reviews });
  }

  // FORCE_SEED runs replace the catalog wholesale, so prune any products and
  // categories left over from a previous catalog. Product cascades to its
  // images, reviews, and wishlist items; Category needs its products gone
  // first (no onDelete on the Product->Category relation, so RESTRICT).
  if (process.env.FORCE_SEED === "true") {
    const newProductIds = catalogProducts.map((p) => p.id);
    const newCategorySlugs = categories.map((c) => c.slug);
    const stalePrd = await prisma.product.deleteMany({
      where: { id: { notIn: newProductIds } },
    });
    const staleCat = await prisma.category.deleteMany({
      where: { slug: { notIn: newCategorySlugs } },
    });
    if (stalePrd.count > 0 || staleCat.count > 0) {
      console.log(
        `[seed] Removed stale catalog rows: ${stalePrd.count} products, ${staleCat.count} categories.`,
      );
    }
  }

  const totalVariants = await prisma.productVariant.count();
  const totalReviews = await prisma.review.count();
  console.log(
    `Seeded ${categories.length} categories, ${catalogProducts.length} products, ${totalVariants} variants, ${totalReviews} reviews.`,
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
