import { existsSync } from "node:fs";
import { join } from "node:path";
import { PrismaClient } from "@prisma/client";
import { categories, catalogProducts } from "../app/_data/mock";
import { REVIEW_AUTHORS, reviewPoolForCategory } from "../app/_data/review-content";
import { DEPARTMENT_TINTS, DESIGN_TINTS } from "../app/_lib/taxonomy-tint";

const departments = [
  { slug: "men",   name: "Men",   navLabel: "Men",   tileName: "Men",   note: null, subName: "Oversized Graphic T-Shirts", sortOrder: 0 },
  { slug: "women", name: "Women", navLabel: "Women", tileName: "Women", note: null, subName: "Oversized Graphic T-Shirts", sortOrder: 1 },
  { slug: "plain", name: "Plain T-Shirts (Unisex)", navLabel: "Plain Tees", tileName: "Plain T-Shirts", note: "Unisex", subName: null, sortOrder: 2 },
  { slug: "accessories", name: "Accessories", navLabel: "Accessories", tileName: "Accessories", note: null, subName: null, sortOrder: 3 },
] as const;

/** Design display names and their department. Slugs `cat` and `dino` are the
 *  two that already ship and are deliberately not renamed (spec decision 6). */
const designs = [
  ["bear", "Bear", "women"], ["cat", "Cats", "women"], ["dino", "Dino", "women"],
  ["dog", "Dog", "women"], ["feathers", "Feathers", "women"], ["heart", "Heart", "women"],
  ["just-grow", "Just Grow", "women"], ["looney", "Looney", "women"], ["panda", "Panda", "women"],
  ["penguin", "Penguin", "women"], ["sealovers", "Sealovers", "women"], ["snoopy", "Snoopy", "women"],
  ["stitch", "Stitch", "women"], ["butterfly", "Butterfly", "women"], ["love", "Love", "women"],
  ["paris", "Paris", "women"],
  ["car", "Car", "men"], ["simpsons", "Simpsons", "men"],
  ["oversized", "Oversized", "plain"], ["regular", "Regular", "plain"],
  ["tote", "Tote", "accessories"], ["cap", "Cap", "accessories"], ["socks", "Socks", "accessories"],
] as const satisfies ReadonlyArray<readonly [string, string, string]>;

// Load Next.js-convention env files for local runs (`tsx prisma/seed.ts`).
// On Vercel/CI, DATABASE_URL is already in process.env and these files are
// absent, so this is a no-op.
for (const file of [".env", ".env.local"]) {
  if (existsSync(file)) process.loadEnvFile(file);
}

const prisma = new PrismaClient();

// Join path segments under public/. Used by resolveVariantImages() below to
// probe for real product photos before falling back to a demo SVG. Generate
// demos with: npx tsx scripts/generate-demo-images.ts
function publicPath(...parts: string[]): string {
  return join(process.cwd(), "public", ...parts);
}

// Stable per-product RNG so reseeds produce the same data.
function rngFromId(id: string): () => number {
  let h = 2166136261 >>> 0;
  for (let i = 0; i < id.length; i++) {
    h ^= id.charCodeAt(i);
    h = Math.imul(h, 16777619) >>> 0;
  }
  return () => {
    h = (Math.imul(h, 1664525) + 1013904223) >>> 0;
    return h / 0xffffffff;
  };
}

function pick<T>(arr: T[], rng: () => number): T {
  return arr[Math.floor(rng() * arr.length)];
}

// Short, consistent default description for the T-shirt catalog (rendered as
// markdown on the product page). Product-agnostic so every item reads the same.
const DEFAULT_DESCRIPTION = `Premium 220 GSM T-Shirt made with a comfortable 65% cotton and 35% polyester blend. Designed for everyday wear with a soft feel, durable fabric, and a clean modern fit. The material is breathable, long-lasting, and perfect for casual outfits, streetwear, or high-quality DTF printed designs.

**Wash Care:** Wash inside out with cold or normal water. Use hand wash or gentle machine wash. Do not bleach, tumble dry, or iron directly on the print. Dry in shade to maintain fabric quality and print durability.`;

// Resolve variant image files under public/products/<productId>/<colorSlug>/<role>/1.jpg..8.jpg.
// Falls back to a single demo SVG so a bare checkout still has an image.
function resolveVariantImages(productId: string, colorSlug: string, role: "card" | "detail"): string[] {
  const urls: string[] = [];
  for (let n = 1; n <= 8; n++) {
    const candidates = [`${n}.jpg`, `${n}.jpeg`, `${n}.png`, `${n}.webp`];
    const found = candidates.find((file) =>
      existsSync(publicPath("products", productId, colorSlug, role, file)),
    );
    if (!found) break;
    urls.push(`/products/${productId}/${colorSlug}/${role}/${found}`);
  }
  if (urls.length === 0) {
    // Demo fallback: main.svg at the product root (generated by scripts/generate-demo-images.ts).
    urls.push(`/products/${productId}/main.svg`);
  }
  return urls;
}

function plainStockFor(colorSlug: string, size: string): number {
  const rng = rngFromId(`plain:${colorSlug}:${size}`);
  return 5 + Math.floor(rng() * 21); // 5..25
}

function designStockFor(slug: string): number {
  const rng = rngFromId(`design:${slug}`);
  return 10 + Math.floor(rng() * 41); // 10..50 — a print batch typically covers many units
}

async function main() {
  const existingDepartmentCount = await prisma.department.count();
  if (existingDepartmentCount > 0 && process.env.FORCE_SEED !== "true") {
    console.log(
      `[seed] Skipping: ${existingDepartmentCount} departments already present. ` +
      `Set FORCE_SEED=true to override.`,
    );
    return;
  }

  if (existingDepartmentCount > 0) {
    console.log(
      `[seed] FORCE_SEED=true detected; reseeding over ${existingDepartmentCount} existing departments.`,
    );
  }

  // Departments and designs. Tints come from DEPARTMENT_TINTS/DESIGN_TINTS so
  // the seed and the contrast gate cannot disagree. The
  // 20260830120000_taxonomy_foundation migration already INSERTs the 4
  // departments, but they're upserted here too so `db:push` + `db:seed`
  // works on a fresh database and a reseed is self-sufficient. `cat` and
  // `dino` are the two designs the mock catalog ships; `image` is left out
  // of their `update` payload so an image set by a previous seed/admin edit
  // survives a reseed instead of being nulled out.
  const departmentByDesign = new Map<string, string>();
  for (const d of departments) {
    await prisma.department.upsert({
      where: { slug: d.slug },
      update: { name: d.name, navLabel: d.navLabel, tileName: d.tileName, note: d.note, subName: d.subName, hex: DEPARTMENT_TINTS[d.slug], sortOrder: d.sortOrder },
      create: { slug: d.slug, name: d.name, navLabel: d.navLabel, tileName: d.tileName, note: d.note, subName: d.subName, hex: DEPARTMENT_TINTS[d.slug], sortOrder: d.sortOrder },
    });
  }

  for (const [slug, name, departmentSlug] of designs) {
    const hex = DESIGN_TINTS[slug];
    if (!hex) throw new Error(`[seed] no tint for design "${slug}"`);
    departmentByDesign.set(slug, departmentSlug);
    await prisma.design.upsert({
      where: { slug },
      update: { name, departmentSlug, hex },
      create: { slug, name, departmentSlug, hex, image: null },
    });
  }

  // DTF designs — one row per distinct design the catalog uses. Quantity is
  // set only on first create; a reseed never overwrites an admin-edited count.
  const designIdBySlug = new Map<string, string>();
  const distinctDesigns = new Map(catalogProducts.map((p) => [p.design.slug, p.design]));
  for (const d of distinctDesigns.values()) {
    const row = await prisma.dtfDesign.upsert({
      where: { slug: d.slug },
      update: { name: d.name },
      create: { name: d.name, slug: d.slug, quantity: designStockFor(d.slug) },
    });
    designIdBySlug.set(d.slug, row.id);
  }

  // Plain T-shirt stock — one row per distinct (colorSlug,size) the catalog
  // offers. Same create-only quantity rule as designs above.
  const distinctPlainCells = new Map<string, { color: string; colorSlug: string; size: string }>();
  for (const p of catalogProducts) {
    for (const v of p.variants) {
      for (const s of v.sizes) {
        distinctPlainCells.set(`${v.colorSlug}::${s.size}`, { color: v.color, colorSlug: v.colorSlug, size: s.size });
      }
    }
  }
  for (const cell of distinctPlainCells.values()) {
    await prisma.plainTshirtStock.upsert({
      where: { colorSlug_size: { colorSlug: cell.colorSlug, size: cell.size } },
      update: { color: cell.color },
      create: { color: cell.color, colorSlug: cell.colorSlug, size: cell.size, quantity: plainStockFor(cell.colorSlug, cell.size) },
    });
  }

  for (const p of catalogProducts) {
    await prisma.product.upsert({
      where: { id: p.id },
      update: {
        name: p.name, price: p.price, originalPrice: p.originalPrice ?? null,
        description: DEFAULT_DESCRIPTION, designSlug: p.category,
        departmentSlug: departmentByDesign.get(p.category)!,
        dtfDesignId: designIdBySlug.get(p.design.slug)!,
      },
      create: {
        id: p.id, name: p.name, price: p.price, originalPrice: p.originalPrice ?? null,
        description: DEFAULT_DESCRIPTION, designSlug: p.category,
        departmentSlug: departmentByDesign.get(p.category)!,
        dtfDesignId: designIdBySlug.get(p.design.slug)!,
      },
    });

    // Rebuild variants (delete cascades to VariantImage + VariantSizeStock).
    await prisma.productVariant.deleteMany({ where: { productId: p.id } });
    for (let vi = 0; vi < p.variants.length; vi++) {
      const v = p.variants[vi];
      const variant = await prisma.productVariant.create({
        data: {
          productId: p.id,
          color: v.color,
          colorSlug: v.colorSlug,
          swatchHex: v.swatchHex ?? null,
          sku: v.sku ?? null,
          price: v.price ?? null,
          originalPrice: v.originalPrice ?? null,
          sortOrder: vi,
          archived: false,
        },
      });

      const cardUrls = resolveVariantImages(p.id, v.colorSlug, "card");
      const detailUrls = resolveVariantImages(p.id, v.colorSlug, "detail");
      const imageRows = [
        ...cardUrls.map((url, i) => ({ variantId: variant.id, url, role: "CARD", sortOrder: i })),
        ...detailUrls.map((url, i) => ({ variantId: variant.id, url, role: "DETAIL", sortOrder: i })),
      ];
      await prisma.variantImage.createMany({ data: imageRows });

      await prisma.variantSizeStock.createMany({
        data: v.sizes.map((s) => ({ variantId: variant.id, size: s.size })),
      });
    }

    // Reviews (product-level, shared across colors) — unchanged logic, keyed on p.id.
    await prisma.review.deleteMany({ where: { productId: p.id } });
    const rng = rngFromId(p.id + ":reviews");
    const count = 5 + Math.floor(rng() * 6);
    const reviews = Array.from({ length: count }, () => {
      const daysAgo = Math.floor(rng() * 90);
      const createdAt = new Date(Date.now() - daysAgo * 86400_000);
      const tpl = pick(reviewPoolForCategory(p.category), rng);
      return {
        productId: p.id, authorName: pick(REVIEW_AUTHORS, rng),
        rating: tpl.rating, title: tpl.title, body: tpl.body,
        createdAt, synthetic: true, approved: true,
      };
    });
    await prisma.review.createMany({ data: reviews });
  }

  // FORCE_SEED runs replace the catalog wholesale, so prune any products and
  // designs left over from a previous catalog. Product cascades to its
  // images, reviews, and wishlist items; Design needs its products gone
  // first (no onDelete on the Product->Design relation, so RESTRICT).
  if (process.env.FORCE_SEED === "true") {
    const newProductIds = catalogProducts.map((p) => p.id);
    const newDesignSlugs = designs.map(([slug]) => slug);
    const stalePrd = await prisma.product.deleteMany({
      where: { id: { notIn: newProductIds } },
    });
    const staleDesign = await prisma.design.deleteMany({
      where: { slug: { notIn: newDesignSlugs } },
    });
    if (stalePrd.count > 0 || staleDesign.count > 0) {
      console.log(
        `[seed] Removed stale catalog rows: ${stalePrd.count} products, ${staleDesign.count} designs.`,
      );
    }
  }

  const totalVariants = await prisma.productVariant.count();
  const totalReviews = await prisma.review.count();
  console.log(
    `Seeded ${categories.length} categories, ${catalogProducts.length} products, ${totalVariants} variants, ${totalReviews} reviews.`,
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
